### ISSUE TITLE
Crash in data source `apstra_datacenter_routing_zones`

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#204]
The following configuration:

```hcl
data apstra_datacenter_routing_zones all {
blueprint_id = "b726704d-f80e-4733-9103-abd6ccd8752c"
}
```

Did this:

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x177ddad]

goroutine 56 [running]:
terraform-provider-apstra/apstra/blueprint.(*DatacenterRoutingZone).Query(0x0, {0x19df266, 0xf}, {0x19da3bb, 0x8})
        terraform-provider-apstra/apstra/blueprint/datacenter_routing_zone.go:278 +0x6d
terraform-provider-apstra/apstra.(*dataSourceDatacenterRoutingZones).Read(0xc00021a000, {0x1b2ab60, 0xc0000ee240}, {{{{0x1b2f588, 0xc000737110}, {0x18b9920, 0xc000736cf0}}, {0x1b320a0, 0xc0003b5740}}, {{{0x0, ...}, ...}, ...}}, ...)
        terraform-provider-apstra/apstra/data_source_datacenter_routing_zones.go:79 +0x285
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadDataSource(0xc00015f760, {0x1b2ab60, 0xc0000ee240}, 0xc0007361e0, 0xc000017650)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_readdatasource.go:75 +0x4ad
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadDataSource(0xc00015f760, {0x1b2ab60?, 0xc000830030?}, 0xc00082e000)
        github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_readdatasource.go:52 +0x42f
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadDataSource(0xc0001d6aa0, {0x1b2ab60?, 0xc000226000?}, 0xc00013e140)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:656 +0x403
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadDataSource_Handler({0x19a75c0?, 0xc0001d6aa0}, {0x1b2ab60, 0xc000226000}, 0xc00027e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001d41e0, {0x1b2f878, 0xc000007380}, 0xc0005ad8c0, 0xc000352c90, 0x2098010, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001d41e0, {0x1b2f878, 0xc000007380}, 0xc0005ad8c0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
```

**Comment by chrismarget-j** [comment]
Closed by #205
