### ISSUE TITLE
Crash in v0.52.4

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#584]
```
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-apstra_v0.52.4 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16706ef]
goroutine 81 [running
github.com/Juniper/terraform-provider-apstra/apstra/blueprint.(*DeviceAllocationSystemAttributes).setTags(0xc0001e4780, {0x1cad618, 0xc0003ff0e0}, 0xc000496100?, 0xc000044420?, {0xc000044420, 0x13}, 0xc0005d56b8)
        github.com/Juniper/terraform-provider-apstra/apstra/blueprint/device_allocation_system_attributes.go:432 +0x8f
github.com/Juniper/terraform-provider-apstra/apstra/blueprint.(*DeviceAllocationSystemAttributes).Set(0xc0001e4780, {0x1cad618, 0xc0003ff0e0}, 0x0, 0xc0003ff0e0?, {0xc0?, {0xc000044420?, 0xc000606b60?}}, 0x19d01a0?)

        github.com/Juniper/terraform-provider-apstra/apstra/blueprint/device_allocation_system_attributes.go:298 +0x5e6

github.com/Juniper/terraform-provider-apstra/apstra/blueprint.(*DeviceAllocation).SetSystemAttributes(0xc0005e8700, {0x1cad618, 0xc0003ff0e0}, 0xc000044420?, 0x13?, 0xc0005d56b8)

        github.com/Juniper/terraform-provider-apstra/apstra/blueprint/device_allocation.go:766 +0x49f

github.com/Juniper/terraform-provider-apstra/apstra.(*resourceDeviceAllocation).Create(0xc0003e1008, {0x1cad618, 0xc0003ff0e0}, {{{{0x1cb4838, 0xc0005f48a0}, {0x19c1de0, 0xc0005f4330}}, {0x1cb7ee0, 0xc0000deaf0}}, {{{0x1cb4838, ...}, ...}, ...}, ...}, ...)

        github.com/Juniper/terraform-provider-apstra/apstra/resource_datacenter_device_allocation.go:146 +0xc65

github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0xc0003f61a0, {0x1cad618, 0xc0003ff0e0}, 0xc0000ef590, 0xc0000ef530)

        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_createresource.go:101 +0x578

github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc0005fd6e8?, {0x1cad618, 0xc0003ff0e0}, 0xc0005d4410, 0xc0000ef6e8)

        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_applyresourcechange.go:57 +0x4a5

github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc0003f61a0, {0x1cad618?, 0xc0003fefc0?}, 0xc0005d4370)

        github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_applyresourcechange.go:55 +0x3ff

github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc0002d4be0, {0x1cad618?, 0xc0003fe4b0?}, 0xc00027e000)

        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/tf6server/server.go:845 +0x3d0

github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x1aeace0?, 0xc0002d4be0}, {0x1cad618, 0xc0003fe4b0}, 0xc0000d8000, 0x0)

        github.com/hashicorp/terraform-plugin-go@v0.21.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x169

google.golang.org/grpc.(*Server).processUnaryRPC(0xc000225000, {0x1cad618, 0xc0003fe420}, {0x1cb5b80, 0xc0003f6ea0}, 0xc0005c8240, 0xc0003f8000, 0x231b718, 0x0)

        google.golang.org/grpc@v1.61.0/server.go:1385 +0xe03

google.golang.org/grpc.(*Server).handleStream(0xc000225000, {0x1cb5b80, 0xc0003f6ea0}, 0xc0005c8240)

        google.golang.org/grpc@v1.61.0/server.go:1796 +0xfec

google.golang.org/grpc.(*Server).serveStreams.func2.1()

        google.golang.org/grpc@v1.61.0/server.go:1029 +0x8b

created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 41

        google.golang.org/grpc@v1.61.0/server.go:1040 +0x135
 
Error: The terraform-provider-apstra_v0.52.4 plugin crashed!
 
This is always indicative of a bug within the plugin. It would be immensely

helpful if you could report the crash with the plugin's maintainers so that it

can be fixed. The output above should help diagnose the issue.
```

**Comment by chrismarget-j** [comment]
closed by #585
