### ISSUE TITLE
unsupported apstra version causes crash

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/terraform-provider-apstra#95]
Found by Adam Jarvis (hilarious formatting by Microsoft Teams):
```
ajarvis@ajarvis-mbp ZF % terraform plan Planning failed. Terraform encountered an error while generating this plan. ╷ │ Error: Plugin did not respond │ │ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details. ╵ Stack trace from the terraform-provider-apstra_v0.15.0 plugin: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1032629c0] goroutine 12 [running]: github.com/Juniper/apstra-go-sdk/apstra.(*Client).logStr(...) github.com/Juniper/apstra-go-sdk@v0.0.0-20230522110948-d674c2561777/apstra/logging.go:20 github.com/Juniper/apstra-go-sdk/apstra.ClientCfg.NewClient({{0x14000490450, 0x12}, {0x14000034948, 0x5}, {0x1400003494e, 0x5}, 0x0, {0x1036a7e00, 0x0}, 0x140005b1a10, ...}) github.com/Juniper/apstra-go-sdk@v0.0.0-20230522110948-d674c2561777/apstra/client.go:205 +0x680 terraform-provider-apstra/apstra.(*Provider).Configure(0x14000322b70, {0x1036ad038, 0x140005b03c0}, {{0x1400040e338, 0x5}, {{{0x1036b1760, 0x140005b1500}, {0x10358b0a0, 0x140005b0f90}}, {0x1036b3d50, ...}}}, ...) terraform-provider-apstra/apstra/provider.go:185 +0x274 github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ConfigureProvider(0x140000c5760, {0x1036ad038, 0x140005b03c0}, 0x14000596c40, 0x14000596bc0) github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/fwserver/server_configureprovider.go:15 +0xc8 github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ConfigureProvider(0x140000c5760, {0x1036ad038?, 0x140005b0270?}, 0x5?) github.com/hashicorp/terraform-plugin-framework@v1.2.0/internal/proto6server/server_configureprovider.go:36 +0x2b0 github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ConfigureProvider(0x140001aaa00, {0x1036ad038?, 0x140005a9a40?}, 0x14000596a00) github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/tf6server/server.go:527 +0x250 github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ConfigureProvider_Handler({0x103672580?, 0x140001aaa00}, {0x1036ad038, 0x140005a9a40}, 0x1400041a3f0, 0x0) github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:331 +0x170 google.golang.org/grpc.(*Server).processUnaryRPC(0x140001a61e0, {0x1036b1a38, 0x140003824e0}, 0x14000289680, 0x14000322cc0, 0x103be0c78, 0x0) google.golang.org/grpc@v1.53.0/server.go:1336 +0xbac google.golang.org/grpc.(*Server).handleStream(0x140001a61e0, {0x1036b1a38, 0x140003824e0}, 0x14000289680, 0x0) google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c google.golang.org/grpc.(*Server).serveStreams.func1.2() google.golang.org/grpc@v1.53.0/server.go:965 +0x84 created by google.golang.org/grpc.(*Server).serveStreams.func1 google.golang.org/grpc@v1.53.0/server.go:963 +0x28c Error: The terraform-provider-apstra_v0.15.0 plugin crashed! This is always indicative of a bug within the plugin. It would be immensely helpful if you could report the crash with the plugin's maintainers so that it can be fixed. The output above should help diagnose the issue.
```

**Comment by chrismarget-j** [comment]
The issue boils down to: When logging is unconfigured (nil `logger` and log threshold `0`), a priority `0` log message (which is created in this case) leads to a nil pointer dereference in the SDK logging code.

While the provider probably shouldn't produce that condition, it's better fixed in the SDK.
